// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieFinder.Database.Context;

#nullable disable

namespace MovieFinder.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241215220403_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MovieFinder.Database.Entities.WatchedMovieEntity", b =>
                {
                    b.Property<int>("WatchedMovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApiMovieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Vote")
                        .HasColumnType("INTEGER");

                    b.HasKey("WatchedMovieId");

                    b.HasIndex("ApiMovieId")
                        .IsUnique();

                    b.ToTable("WatchedMovies");
                });
#pragma warning restore 612, 618
        }
    }
}
